### ISSUE TITLE
Data source to retrieve maas_machine information

### ISSUE THREAD

**Issue by anpolychrono** [maas/terraform-provider-maas#141]
Is there any data source where you can give the **hostname** of the machine and retrieve all the information discovered from MAAS after commissioning a machine ?

I am interested for getting all the physical NICs so I can generate my own netplan by renaming interfaces and populating interface names in services running in the machine. 

Something like this but only the hostname as a required:

```hcl
data maas_network_interface_physical {
  hostname = "node1"
}
```

and as a result a list of all NICs with the mac-address etc.

**Comment by skatsaounis** [comment]
Hi @anpolychrono,

There is no such resource but we could consider adding it. That resource could be something like this:

```tf
data "maas_machine_network_interfaces" "example" {
  hostname = ""
  # or
  pxe_mac_address = ""
}
```

And the return value is something debatable. It will definitely be BootInterface, Interfaces of the machine, but the returned information requires some thought. Is it going to be the MAC address and the type of each interface? Is it going to be their ids so that user can do something like the following?

```tf
data "maas_machine_network_interfaces" "example" {
  hostname = "mymachine.maas"
}

locals {
  physical_nics = {for k, v in data.maas_machine_network_interfaces.example.interfaces: k => v if v.type == "physical" }
}

data "maas_network_interface_physical" "physical_nics" {
  for_each = local.physical_nics
  machine  = data.maas_machine_network_interfaces.example.id
  name     = each.key
}
```
It will require some thought but it is doable. In any case, we are more than happy to review incoming PRs if you are up for contributing to the provider :slightly_smiling_face:

**Comment by anpolychrono** [comment]
Hi @skatsaounis thanks for the update. 

At least in my use case the approach you suggest to return PHYSICAL NIC IDs which can be used after to get more information on each specific interface, looks ok to me. 

I will be more than happy to contribute here, let me know what is needed.
