### ISSUE TITLE
(v1.0.0) JSON error when attempting to import an existing machine.

### ISSUE THREAD

**Issue by john-terrell** [maas/terraform-provider-maas#16]
I'm getting this error when attempting to import a machine using Maas v3.2 and Provider v1.0.0:

```shell
$ TF_LOG=ERROR terraform import maas_machine.compute01 rested-tiger.maas
2022-07-13T15:13:28.033-0600 [ERROR] vertex "maas_machine.compute01 (import id \"rested-tiger.maas\")" error: json: cannot unmarshal array into Go value of type string
╷
│ Error: json: cannot unmarshal array into Go value of type string
│ 
│ 
```

**Comment by tFable** [comment]
Hello,

I cam here to report the same issue and I'm now I see that there is a ticket for this since July 2022 🙂 

I'm having this same issue on 1.1.0 with Terraform 1.4.0

```
maas_machine.mahine2: Importing from ID "machine"...
╷
│ Error: json: cannot unmarshal array into Go value of type string
│ 
│ 
╵
```

Interestingly, I was able to import a couple of machines with the exact same versions of the provider and TF but it looks like I am no longer able to. This can totally be because of specifics with other machines triggering this error, of course.

Importing of instances appears to work.

Any help to solve this would be greatly appreciated. Without the ability to import machines, any machines configured outside of TF must be rebuilt if we wanted them added to TF.

Thanks for your help!

**Comment by skatsaounis** [comment]
Hi both,

With this PR https://github.com/maas/terraform-provider-maas/pull/92, the new version of gomaasclient is used by the provider, which includes a fix on the parsing of a couple of machine fields. I am closing this ticket but please re-open if you hit the issue again so as to eliminate any remaining erroneous field.

**Comment by TirasG** [comment]
Hey @skatsaounis unfortunately it appears this bug still exists. 

Not OP but encountering it on my own instance of MaaS.
`terraform -v`:
```

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/maas/maas v1.3.0
```
`terraform apply`:
```
2023-10-03T09:09:20.753-0700 [ERROR] vertex "maas_machine.testSystem (import id \"*****\")" error: json: cannot unmarshal array into Go value of type string
2023-10-03T09:09:20.753-0700 [ERROR] vertex "maas_machine.testSystem (expand)" error: json: cannot unmarshal array into Go value of type string
│ Error: json: cannot unmarshal array into Go value of type string
```

From my own digging into this (with limited Go knowledge) I tracked it down to the [gomaasclient](https://github.com/maas/gomaasclient/blob/b2775d1ca870276e53f3df36ee4f80399f65b3bf/client/machine.go#L98C1-L104C2) `entity.Machine.GetPowerParameters`
```
func (m *Machine) GetPowerParameters(systemID string) (params map[string]string, err error) {
	params = map[string]string{}
	err = m.client(systemID).Get("power_parameters", url.Values{}, func(data []byte) error {
		return json.Unmarshal(data, &params)
	})
	return
}
```
This properly get the JSON from the MaaS API, however when it attempts to unmarshal into a `map[string]string` it will fail.
Some power providers (Such as [IPMI](https://maas.io/docs/api#:~:text=%20Default%3A%20%27OPERATOR%27.-,workaround_flags,-(Workaround%20Flags).%20Choices)) return an array within this object. From what I can tell this is the source of the bug since Go JSON cannot unmarshal an array into a string. Even with an empty array within this option the error still occurs.

I did attempt to fix this on my own however with my limited Go experience I couldn't find a clean solution. From what I could tell, changing this return to `map[string]interface{}` would resolve this as it could unmarshal the JSON array to a GO array. However I'm not sure if this is the best solution (Plus, you'd have to rework how the `maasapiclient` works with the data returned)

Sorry for all this info dump. I just wanted to help out but don't have the GO knowledge to put any real changes in place ._.
Let me know if you need any additional info!

**Comment by UnknownTy** [comment]
Hey @skatsaounis  unfortunately it appears this bug still exists.

Not OP but encountering it on my own instance of MaaS.
`terraform -v`:
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/maas/maas v1.3.0
```
`terraform apply`:
```
2023-10-03T09:09:20.753-0700 [ERROR] vertex "maas_machine.testSystem (import id \"*****\")" error: json: cannot unmarshal array into Go value of type string
2023-10-03T09:09:20.753-0700 [ERROR] vertex "maas_machine.testSystem (expand)" error: json: cannot unmarshal array into Go value of type string
│ Error: json: cannot unmarshal array into Go value of type string
```
From my own digging into this (with limited Go knowledge) I tracked it down to the [gomaasclient](https://github.com/maas/gomaasclient/blob/b2775d1ca870276e53f3df36ee4f80399f65b3bf/client/machine.go#L98C1-L104C2) `entity.Machine.GetPowerParameters`

```
func (m *Machine) GetPowerParameters(systemID string) (params map[string]string, err error) {
	params = map[string]string{}
	err = m.client(systemID).Get("power_parameters", url.Values{}, func(data []byte) error {
		return json.Unmarshal(data, &params)
	})
	return
}
```
This properly get the JSON from the MaaS API, however when it attempts to unmarshal into a `map[string]string` it will fail.
Some power providers (Such as [IPMI](https://maas.io/docs/api#:~:text=%20Default%3A%20%27OPERATOR%27.-,workaround_flags,-(Workaround%20Flags).%20Choices)) return an array within this object. From what I can tell this is the source of the bug since Go JSON cannot unmarshal an array into a string. Even with an empty array within this option the error still occurs.

I did attempt to fix this on my own however with my limited Go experience I couldn't find a clean solution. From what I could tell, changing this return to `map[string]interface{}` would resolve this as it could unmarshal the JSON array to a GO array. However I'm not sure if this is the best solution (Plus, you'd have to rework how the maasapiclient works with the data returned)

Sorry for all this info dump. I just wanted to help out but don't have the GO knowledge to put any real changes in place ._.
Let me know if you need any additional info!

**Comment by skatsaounis** [comment]
Hi @UnknownTy

You were right on your investigation findings and thank you very much for your time. Indeed, the problematic power parameter is the `workaround_flags` of type IPMI. This parameter in contrast with any other is not a `string` but a `[]string`. I developed a solution and I made it work locally with the linked PR: https://github.com/maas/terraform-provider-maas/pull/96

Since this one requires changes to both `gomaasclient` and also to the `power_parameters` field it may delay to get landed but it is definitely a solution. Among other things, we also hit a Terraform SDK limitation, thus the proposed change to the field.

**Comment by UnknownTy** [comment]
Thanks @skatsaounis for the quick turnaround on that!
Glad info I could provide could help out with this old issue.
Was perfect timing as I encountered this issue, dug into it a bit and saw you updated the original issue just a few days later.

Always a wonder to see someone take an idea and do it much better than I could in a language I'm still learning ;)
Cheers.

**Comment by UnknownTy** [comment]
I see https://github.com/maas/terraform-provider-maas/pull/96 was merged into Main.
Tested using a locally built version of the provider:
```
maas_machine.test_machine: Importing from ID "*****"...
maas_machine.test_machine: Import prepared!
  Prepared maas_machine for  import
maas_machine.test_machine: Refreshing state... [id=*****]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Checking `terraform.tfstate` confirms the power_parameters are properly brought in.
Managing the imported state also functioning as expected.

Thanks again @skatsaounis!
