### ISSUE TITLE
Terraform creates vm even if the machine name matches a deployed machine

### ISSUE THREAD

**Issue by jempson** [maas/terraform-provider-maas#80]
When attempting to deploy a machine if the machine names happens to be in the deployed state and the maas instance happens to have a KVM host Terraform will create a VM with a random machine name and deploy with the cloud-init from my repo.

The expected result would be for terraform to error out stating the machine is not in the ready state.  This can happen if a user attempts to re-run a repo which has a machine in the incorrect state.

**Comment by skatsaounis** [comment]
Hi @jempson.

Thank you for opening this issue. Could you please provide more information so as to be able to troubleshoot? I would like to get your .tf file, some evidence of the already deployed machine and also the successful output of `terraform apply` when this issue is happening. Finally, please mention your MAAS and terraform-provider-maas versions.

Thank you
